apiVersion: v1
kind: ConfigMap
metadata:
  name: docai-config
  namespace: docai
data:
  MLFLOW_TRACKING_URI: http://mlflow:5000
  MOCK_TRAINING: "true"
  ENABLE_SALESFORCE: "false"
  ENABLE_SAP: "false"
  ENABLE_RAG: "true"
  METRICS_PUBLIC: "true"
  POSTGRES_HOST: postgres
  POSTGRES_USER: docai_user
  POSTGRES_DB: docai_db
  POSTGRES_PORT: "5432"
  AUTH_DISABLED: "false"
