apiVersion: v1
kind: Service
metadata:
  name: docai-service
  namespace: docai
spec:
  selector:
    app: docai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
